import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Badge, Button, Container } from "react-bootstrap";

// components
import Why_Us from "../components/Why_Us";
import MemberWith from "../components/MemberWith";
import CTA from "../components/CTA";
import Counts from "../components/Counts";
import AboutUs from "../components/AboutUs";
import NewPatients from "../components/NewPatients";
import FAQ from "../components/FAQ";
import Appointment from "../components/Appointment";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id={styles.hero}>
        <Container className={styles.container}>
          <div>
            <h1>Welcome to Medical</h1>
            <h2 className="mb-4">
              Consequuntur sunt aut quasi enim aliquam quae harum pariatur
            </h2>
            <a href="#">
              <Badge pill className="py-2 px-4">
                Get Started
              </Badge>
            </a>
          </div>
        </Container>
      </section>
      <Why_Us />

      <main className={styles.main}>
        <AboutUs />
        <MemberWith />
        <CTA />
        <NewPatients />
        <Counts />
        <Appointment />
        <FAQ />
        <Footer />
      </main>
    </div>
  );
}
